# silverbullet.yml
http:
  routers:
    silverbullet:
      rule: "Host(`silverbullet.fzmacair.local`)"
      service: silverbullet-service
      middlewares:
        # Uncomment this to enable HTTPS redirection
        # - common-redirect-to-https
        # - tinyauth-auth

  services:
    silverbullet-service:
      loadBalancer:
        servers:
          - url: "http://fzsilverbullet:3000"
