RUN apt-get update && apt-get install -y postgresql-17-pgvector
COPY --from=vchord_scratch / /
COPY include/pgvector/post-init.sh /docker-entrypoint-initdb.d/01-pgvector-init.sh
CMD ["postgres", "-c", "shared_preload_libraries=vchord,vector"]
